encryptionsalt: v1:1gjxHZM1OXM=:v1:vTvZc6NcHCXRUk4B:PQ2di+bBUp8JkPLOvPYrgLuXy51LFA==
config:
  sonq:GITHUB_EMAIL: yannic.inselmann@gmail.com
  sonq:GITHUB_PASSWORD:
    secure: v1:YK3U+Zh+PeMb4lMT:39/j1stTIzIsmH5z14mMoZsrhKNHlBQnOGgxeoWFMOUaOlaT2SOqXux9icYCEteeRU/pOzO93do=
  sonq:GITHUB_USERNAME:
    secure: v1:AE7Nrd04uO/GpSqu:Ur8q7uOF+xmn6Ptj1nCn6xZ9/YcvS06r
  sonq:namespace: production
